### PR TITLE
Fix ecdhUnsafe for bindings

### PR DESCRIPTION
**Pull request by fanatid**
Issue #138 

@vpulim can you test this changes?

### CODE REVIEW

**Comment by vpulim** [comment]
Awesome! This seems to have fixed the issue. Thanks for the fast turnaround.

**Comment by fanatid** [comment]
Thanks for tests. Published as `3.6.1`
`3.6.0` marked as depricated

**Comment by holgerd77** [comment]
Hi @fanatid, the `secp256k1.ecdhUnsafe` function seems not to be available on `v4.0.1` any more, see following test output:

```shell
$ node
Welcome to Node.js v12.15.0.
Type ".help" for more information.
> const secp256k1 = require('secp256k1')
undefined
> secp256k1.ecd
secp256k1.ecdh          secp256k1.ecdsaRecover  secp256k1.ecdsaSign     secp256k1.ecdsaVerify

> secp256k1.ecd
secp256k1.ecdh          secp256k1.ecdsaRecover  secp256k1.ecdsaSign     secp256k1.ecdsaVerify

> secp256k1.ecdhUnsafe
undefined
> secp256k1.ecdh
[Function: ecdh]
````

Was this an intentional change and can you explain what happened? We are stumbling upon this on the devp2p library trying to update the `secp256k1` version here https://github.com/ethereumjs/ethereumjs-devp2p/pull/68

**Comment by fanatid** [comment]
Hi @holgerd77! `ecdhUnsafe` was removed since secp256k1 upstream now allow custom functions for ECDH.
README have example how receive same data as from `ecdhUnsafe` in 3.x https://github.com/cryptocoinjs/secp256k1-node/tree/v4.0.1#get-x-point-of-ecdh

**Comment by holgerd77** [comment]
@fanatid thanks, great! 😊

**Pull request merged**
