### PR TITLE
fix publicKeyConvert

### PR DESCRIPTION
**Pull request by fanatid**
@Kagami thanks for note. #46

### CODE REVIEW

**Comment by Kagami** [comment]
What if user specified `compressed = true`?

**Comment by fanatid** [comment]
`outputlen` not only input, it also output for size serialized public key (if it would be only for input, it not be a pointer)
[secp256k1_ec_pubkey_serialize](https://github.com/bitcoin/secp256k1/blob/master/src/secp256k1.c#L168)
[secp256k1_eckey_pubkey_serialize](https://github.com/bitcoin/secp256k1/blob/master/src/eckey_impl.h#L36)

**Comment by Kagami** [comment]
But the size of _output_ is 33 in case of `compressed = true` if I understand everything correctly.

**Comment by fanatid** [comment]
Yes, compressed public key size is 33 bytes (odd flag -- 1 byte and X point -- 32 bytes). But if we pass SECP256K1_EC_COMPRESSED in the flags [we will get outputlen equal to 33](https://github.com/bitcoin/secp256k1/blob/master/src/eckey_impl.h#L44) and create buffer that contain 33 bytes.

**Pull request merged**
