### PR TITLE
(WIP) Schnorr signatures

### PR DESCRIPTION
**Pull request by fanatid**
Original issue: #97 
Any comments about API?

(I would prefer use named arguments instead options and change arguments order in verify/recover, but it will be major changes for ECDSA sign/verify/recover :disappointed:)

### CODE REVIEW

**Comment by dcousens** [comment]
Is this the same as the C API?

**Comment by fanatid** [comment]
@dcousens yes, API is same as in [secp256k1_schnorr.h](https://github.com/bitcoin-core/secp256k1/blob/7a49cacd3937311fcb1cb36b6ba3336fca811991/include/secp256k1_schnorr.h) in bitcoin-core/secp256k1

**Comment by dcousens** [comment]
light utACK 4fe0b3d,  havent't verified the actual binding code,  but on the surface the rest looks good.

**Comment by fanatid** [comment]
Blocked by https://github.com/bitcoin-core/secp256k1/pull/416

**Comment by apoelstra** [comment]
The Schnorr API is going to change in future, I'd advise against people using it downstream.

**Comment by fanatid** [comment]
@apoelstra when you planning to change Schnorr API? In next 3month? In next year?
Do you know how API will be changed?
Thank you.

**Comment by apoelstra** [comment]
cc @sipa is there anything specific we can say here?

**Pull request closed without merging**
