### PR TITLE
Fix pad32 function

### PR DESCRIPTION
**Pull request by Kagami**
See #11

### CODE REVIEW

**Comment by wanderer** [comment]
awesome thanks @Kagami !

**Comment by Kagami** [comment]
Could you release it on npm please?

**Comment by Kagami** [comment]
@wanderer ping?

**Comment by wanderer** [comment]
awwww sorry! got buried pushing now

**Comment by wanderer** [comment]
ok v0.0.15 is up

**Comment by Kagami** [comment]
Thanks!

**Pull request merged**
