### PR TITLE
Add support for node 0.10

### PR DESCRIPTION
**Pull request by Kagami**
This PR adds support for node 0.10 since some LTS distros still use it, and used addon wrapper `nan` supports it.

Actually everything is fine, just fix for few quirks and bugs.

### CODE REVIEW

**Comment by fanatid** [comment]
Thanks! But can you also fix README.md? Change 0.11 to 0.10 and fix npm badge (need to replace secp256k1-node to secp256k1).

**Comment by Kagami** [comment]
Done.

**Comment by Kagami** [comment]
Any plans to make a new npm release?

**Comment by fanatid** [comment]
Yep, sure. Published in 2.0.4

**Pull request merged**
