### PR TITLE
use Buffer.alloc instead of copy

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by fanatid** [comment]
If you want this, we need `safe-buffer`, because we support `>= 4.0.0`
`alloc` was introduced in `4.6.0` IIRC

**Comment by dcousens** [comment]
@fanatid the file uses `safe-buffer`:

``` js
var Buffer = require('safe-buffer').Buffer
```

**Comment by fanatid** [comment]
haha, I forget about this :D

**Review by fanatid — APPROVED** [review]

**Comment by fanatid** [comment]
btw, we all know that `alloc` return zero buffer, but maybe will more clear set second argument as `0`?

**Comment by dcousens** [comment]
@fanatid set as explicitly `0`

**Pull request merged**
