### PR TITLE
What I had to do to get it to build on Windows 8.1 64bit

### PR DESCRIPTION
**Pull request by tcoulter**
I used suggestions from here: https://github.com/cryptocoinjs/secp256k1-node/issues/20

Specifically: 
- I had to install Pyhon 2.7 on my machine, and add it to the PATH
- I had to install OpenSSL 64 bit at the location above. I got it from [here](http://slproweb.com/products/Win32OpenSSL.html), which is recommended by the [ursa module](https://www.npmjs.com/package/ursa)
- I had to change the x64 architecture specification in `binding.gyp` so that it wasn't special. For some reason those extra variables related to ASM and INT128 caused many compile errors.
- ~~I had to remove the tests running from `npm prepublish` as it runs on `npm install` (at least, when running `npm install` from the secp256k1-node directory), and it would error due to invalid syntax in the istanbul/mocha bat file for windows (I'm not sure which module's responsible).~~

I'm sure my changes -- especially the last two -- aren't up to par, and I don't much understand their significance. But at least this is a start.

### CODE REVIEW

**Comment by wanderer** [comment]
So this almost is ready to go... I talked to @tcoulter earlier and he said we was going to work on cleaning up the bindings.gyp a bit more

**Comment by tcoulter** [comment]
Working on that right now. :)

**Comment by tcoulter** [comment]
@wanderer Alright, I've included the best cleanup I could. It effectively makes all the variables set at the highest scope, so that they can be used in lower scopes. I tried to clean up all the `defines`, but since its an array it doesn't allow for conditions in the same way `variables` does.

**Comment by tcoulter** [comment]
Oh, and I've confirmed it builds for me on Windows and Mac.

**Comment by tcoulter** [comment]
Last outstanding issue might be the tests. I haven't gotten them to run on windows yet.

**Comment by fanatid** [comment]
@tcoulter :+1: 
please make rebase and then we'll see build status on linux :)

**Comment by tcoulter** [comment]
@fanatid What should I rebase against?

**Comment by tcoulter** [comment]
Oh. Duh. Github even gives me a button!

**Comment by fanatid** [comment]
ACK, if it works on windows (sorry I can't check this)
@wanderer if PR is ok for you, please let me now, I want merge it manually for flat history

**Comment by wanderer** [comment]
@fanatid looks good to me!

**Comment by tcoulter** [comment]
@fanatid After you merge, could you push a new version with this change to npm? This is a blocker to making dependent modules install cleanly on Windows. Would love to release Windows support for those modules as soon as possible. Thanks!

**Comment by fanatid** [comment]
@tcoulter Thank you! Published as 3.0.1

**Pull request closed without merging**
