### PR TITLE
default node export

### PR DESCRIPTION
**Pull request by fanatid**
Related issue: #71 
Right now fallback is `elliptic`.

### CODE REVIEW

**Comment by dcousens** [comment]
Why is it wrapped in a function? OOI

**Comment by fanatid** [comment]
This do not give any benefits, I just did not wanted write `module.exports =` twice :)

**Comment by jprichardson** [comment]
What's the purpose of this? The bindings / elliptic don't return compatible APIs. Why not just do to technique as describe in #71?

**Comment by fanatid** [comment]
@jprichardson `secp256k1/bindings`, `secp256k1/elliptic` and `secp256k1/js` have same interface. Right now exporting `./elliptic` in `bindings.js` because `./elliptic` uses for browser (in package.json).
I would like to switch on `./js` and I'll create PR with this after resolving #69.

**Pull request merged**
