### PR TITLE
Implement ecdh and ecdhUnsafe

### PR DESCRIPTION
**Pull request by fanatid**
Related issue: https://github.com/cryptocoinjs/secp256k1-node/issues/59
cc @axic @wanderer

### CODE REVIEW

**Comment by fanatid** [comment]
Benchmark:

```
Set seed: ade8e81b96e62b526846cea277cb457deb7f904d46f12d39a3cd5124a2859962
100% (1000/1000), 3.1s elapsed, eta 0.0s
Create 1000 fixtures
++++++++++++++++++++++++++++++++++++++++++++++++++
Benchmarking: ecdh
--------------------------------------------------
bindings x 5,542 ops/sec ±0.37% (87 runs sampled)
secp256k1js x 167 ops/sec ±0.96% (78 runs sampled)
elliptic x 314 ops/sec ±1.79% (80 runs sampled)
```

elliptic uses endomorphism, secp256k1js not

**Comment by axic** [comment]
Looks great! Is speed the reason you have chosen to implement it from scratch in C and not using publicKeyTweak?

**Comment by fanatid** [comment]
@axic no, `Unsafe` only means that `sha256` not applied to serialized public key.. `pubkey_tweak_mul` doesn't have timing attack resistant.

**Comment by axic** [comment]
Oh great, so you're using the const methods 👍

**Comment by wanderer** [comment]
looks great!

**Pull request merged**
