### PR TITLE
Adds test for a validation error that seckp catches but elliptic does not

### PR DESCRIPTION
**Pull request by wanderer**

### CODE REVIEW

**Comment by wanderer** [comment]
@fanatid I'm not sure of all the parameters that need to be validated on a signature, msg, key triplet, but it looks like there is more than just s,r being zero.  I  think elliptic's `verify` covers the most of them... but i'm not 100% sure yet

**Comment by wanderer** [comment]
@fanatid  also i put back clang!

**Comment by fanatid** [comment]
@wanderer please, don't merge so fast
- in bitcoin/secp256k1 high `s` is not valid signature in verify: [source](https://github.com/bitcoin/secp256k1/blob/c18b869e58aa4d3bff6958f370f6b643d1223c44/src/secp256k1.c#L309)
- not fully agree with removing `r` and `s` is zero check in recover. Should we recover public key for invalid signature? bitcoin/secp256k1 doesn't

**Comment by wanderer** [comment]
> please, don't merge so fast

@fanatid ok; in the future l will not merge until I get a "look good to me" from you. 

> not fully agree with removing r and s is zero check in recover

Elliptic's `verify` does that check [here](https://github.com/indutny/elliptic/blob/cbccbc862bcbb3a0f2ce8021d340e51f785e2ebd/dist/elliptic.js#L2086-L2089) . So we do that check **after**  we do recovery. Does the order in which we check matter?

**Comment by fanatid** [comment]
oh, I didn't see that you added verify to recover, what purpose of this?

**Comment by wanderer** [comment]
Because it checks all the edges cases, Ie. checks that its a valid point. bitcoins seckp does this too in recovery.

**Comment by fanatid** [comment]
Shouldn't we follow for bitcoin secp? Verify only confirm that recovery param was right, I think that library shouldn't do this. If user want he can do it itself.

**Comment by wanderer** [comment]
> Shouldn't we follow for bitcoin secp?

Sure it would be a bit more efficient! We basically need this [logic](https://github.com/bitcoin/secp256k1/blob/1a3e03a348b5a26772c5ee88bad61a2111f58286/src/modules/recovery/main_impl.h#L96-L112).

**Pull request merged**
