### PR TITLE
[Experimental] v4

### PR DESCRIPTION
**Pull request by fanatid**
API draft of v4 where I would like use es6 (with import/export). Any comments are welcome.

### CODE REVIEW

**Comment by jprichardson** [comment]
>  I would like use es6 (with import/export). 

I like the sounds of this!

**Comment by dcousens** [comment]
What was the motivation OOI?

**Comment by fanatid** [comment]
@dcousens the main motivation is stay on the latest version of JS. With ES6 modules tree-shaking will be available.

**Comment by dcousens** [comment]
Sure,  not too early for that?

**Comment by fanatid** [comment]
I think it is not early. At least node v7 already supports [99% of ES2015](http://node.green/). For browsers we will need compile to ES5 a very long time...

**Comment by dcousens** [comment]
Node 7 isn't even out yet?  `import/export` doesn't even work in node@6.0.0.
How is that _not_ early?

**Comment by fanatid** [comment]
Temporary suspended. I will continue when schnorr will be ready.

**Pull request closed without merging**
