### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by wanderer**

### CODE REVIEW

**Comment by fanatid** [comment]
I don't think that we should release 3.0.0 while ecdh not available..

**Comment by fanatid** [comment]
as option, we can implement ours version ecdh with custom hash function (in this case we don't need wait https://github.com/bitcoin/secp256k1/pull/354)

**Comment by wanderer** [comment]
@fanatid What do you think about adding ecdh on later? I would assume it would be a backwards compatible api change (3.1.0)

**Comment by fanatid** [comment]
I agree with this.

**Pull request merged**
