### PR TITLE
Allow bindings compile fail on install

### PR DESCRIPTION
**Pull request by fanatid**
Original issue: #94 
Tested on Linux and Windows, can somebody check on MacOS?

### CODE REVIEW

**Comment by jprichardson** [comment]
Yeah, I can, is there an easy way to check?

**Comment by fanatid** [comment]
```
$ git checkout feature/allow-fail
$ rm -rf node_modules
$ rm src/addon.cc
$ npm install
```

`echo $?` should return `0`

**Comment by jprichardson** [comment]
Worked great!

**Comment by fanatid** [comment]
@jprichardson thank you!
Published in 3.2.0

**Pull request merged**
