### PR TITLE
more functions, secp256k1-browserify merge, tests

### PR DESCRIPTION
**Pull request by fanatid**
Implement more functions / merge with [secp256k1-browserify](https://github.com/wanderer/secp256k1-browserify) / tests.
- [x] Write [API.md](https://github.com/fanatid/secp256k1-node/blob/v0.2.x/API.md)
- [x] Implement all functions with [secp256k1](https://github.com/bitcoin/secp256k1/)
- [x] Approximate to 100% coverage ([ecdsa](https://github.com/cryptocoinjs/ecdsa) as 3rd library)
- [x] Merge with [secp256k1-browserify](https://github.com/wanderer/secp256k1-browserify)
- [x] Implement all functions on [elliptic](https://github.com/indutny/elliptic)
- [x] add [karma](https://github.com/karma-runner/karma), [eslint](https://github.com/eslint/eslint) (with [standard config](https://github.com/feross/eslint-config-standard))
- [x] ~~write examples in API.md~~
- [x] update README.md

@wanderer any thoughts about this?

### CODE REVIEW

**Comment by wanderer** [comment]
@fanatid looks good! 

 One thing that would be good to add to 0.2 is key [serialization function](https://github.com/bitcoin/secp256k1/blob/31994c8e5b8ec6693b2f8678b39d12d65c67067d/include/secp256k1.h#L266) Relate #34 

Also we are already using [standard](https://github.com/wanderer/secp256k1-node/blob/master/package.json#L7) :)

**Comment by wanderer** [comment]
Related #38

**Comment by wanderer** [comment]
@fanatid also I added you as a collaborator so feel free to add this branch to the repo.

**Comment by fanatid** [comment]
- Yep, you already use `standard`, but `standard` itself uses `eslint`, so it's better use `eslint` with _standard-config_.
- What you think about async functions? only `sign`, `verify`, `recover` and `ecdh`?
- I can't implement `secretKeyExport`/`secretKeyImport`, some problems with [lax_der_privatekey_parsing.h
  ](https://github.com/bitcoin/secp256k1/blob/master/contrib/lax_der_privatekey_parsing.h). Maybe you take a look?
- #34 will be solved with function `.publicKeyConvert`

**Comment by wanderer** [comment]
> What you think about async functions? only sign, verify, recover and ecdh

I'm cool with only those being Async. 
Ecdh is just a single EC multiplication so it should be really fast to and probably doesn't need to be async.

> I can't implement secretKeyExport/secretKeyImport

Ok I'll try to take a look today

**Comment by fanatid** [comment]
@Kagami I opened for myself your project [eccrypto](https://github.com/bitchan/eccrypto). Any suggestion about v0.2.x?

**Comment by Kagami** [comment]
@fanatid Do you mean my suggestions regarding `secp256k1-node`? There are few:
- ECDH (already adressed) - #28
- Fix for signatures serialization - #33
- Do strictier input validation as a fool-proof - [like here](https://github.com/bitchan/eccrypto/blob/v1.0.2/index.js#L97-L98) - it wasn't strictly ensured last time I checked

Otherwise I'm quite ok with API and features. `secp256k1-browserify` partially eleminates the need of my own `elliptic` wrapper in [browser.js](https://github.com/bitchan/eccrypto/blob/v1.0.2/browser.js), but it's not that much code and I need separate implementation for browsers for other features anyway.

**Comment by wanderer** [comment]
@fanatid Re on: secretKeyExport/secretKeyImport; Looks like the most recent [secp256k](https://github.com/bitcoin/secp256k1/blob/master/include/secp256k1.h) doesn't even have the secp256k1_ec_privkey_export/import. So just skip those I guess. They just converted privkey to DER and back again anyways.

**Comment by fanatid** [comment]
@Kagami thanks. I'm already implement ecdh and stricter input validation. I"ll check signatures serializations.
@wanderer ec_privkey_(export|import)_der was moved to [contrib/lax_der_privatekey_parsing.h](https://github.com/bitcoin/secp256k1/blob/master/contrib/lax_der_privatekey_parsing.h)
**EDIT**: I update secp256k1 to [e2100ad](https://github.com/bitcoin/secp256k1/tree/e2100ad5b3143be2d2830aca2fb40898d5a3f36f) and implement export/import for secret key.

**Comment by fanatid** [comment]
ok, I think it's all :)
@wanderer now you can merge it!

**Comment by Kagami** [comment]
:+1: for merging this. Hope to see new release soon, great work.

**Comment by wanderer** [comment]
@fanatid awesome work!

**Pull request merged**
