### PR TITLE
Adds Test case that fails on elliptic but works in native code

### PR DESCRIPTION
**Pull request by wanderer**

### CODE REVIEW

**Comment by fanatid** [comment]
It is not elliptic error, we just need extra signature validation

**Comment by wanderer** [comment]
@fanatid yes I have a fix. But currently I'm messing up git.

**Comment by wanderer** [comment]
@fanatid not sure if we should use the solution in #64 or #63 what do you think?

**Comment by fanatid** [comment]
If we want same behavior like `bitcoin/secp256k1` we should use #64, but I found that verify also need a fix...

**Pull request closed without merging**
