### PR TITLE
Update signatureExport/signatureImport

### PR DESCRIPTION
**Pull request by fanatid**
Base PR: https://github.com/cryptocoinjs/secp256k1-node/pull/77

### CODE REVIEW

**Comment by fanatid** [comment]
@wanderer use https://github.com/bitcoinjs/bip66 for encode/decode as we discussed
can you re-check?

**Comment by fanatid** [comment]
@dcousens I'd like raise this topic again, can we move padding to `bitcoinjs/bip66` ?
for removing next lines here:

``` js
var r = Buffer.concat([new Buffer([0]), sigObj.r])
for (var lenR = 33, posR = 0; lenR > 1 && r[posR] === 0x00 && !(r[posR + 1] & 0x80); --lenR, ++posR);

if (sigObj.r.length === 33 && sigObj.r[0] === 0x00) sigObj.r = sigObj.r.slice(1)

r: Buffer.concat([ZERO_BUFFER_32, sigObj.r]).slice(-32)
```

**Comment by wanderer** [comment]
Thank you @fanatid this looks good to me now.  Feel free to merge.

**Comment by fanatid** [comment]
https://github.com/bitcoinjs/bip66/pull/2 was merged, marked temporary as WIP

**Comment by fanatid** [comment]
https://github.com/bitcoinjs/bip66/pull/2 was reverted
@dcousens thank you for `bitcoinjs/bip66`

**Comment by dcousens** [comment]
@fanatid sorry it didn't work out :( entirely...

**Pull request merged**
