### PR TITLE
Introduce signatureImportLax

### PR DESCRIPTION
**Pull request by fanatid**
Implemented proposal from https://github.com/cryptocoinjs/secp256k1-node/issues/83#issuecomment-238404323

### CODE REVIEW

**Comment by jprichardson** [comment]
@dcousens I don't like the name `Lax`, but I don't have any better suggestion... so I'll just go park my bike by the shed 😛

**Comment by dcousens** [comment]
@jprichardson the motivation for the name was purely a derivation of the underlying `ecdsa_signature_parse_der_lax`.

**Comment by dcousens** [comment]
LGTM

**Comment by fanatid** [comment]
Documentation was updated.

**Pull request merged**
