### PR TITLE
Add new entry point: index.js

### PR DESCRIPTION
**Pull request by fanatid**
I think that `try-catch` in `bindings.js` is wrong way.

### CODE REVIEW

**Comment by axic** [comment]
Why do you need a try/catch? Why not just use bindings.js as the entry point and override it for browserify?

**Comment by fanatid** [comment]
Original issue: https://github.com/cryptocoinjs/secp256k1-node/issues/71
`try-catch` is helpful when compilation fail..

**Comment by axic** [comment]
I assumed if compilation fails, the package fails to install?

**Comment by fanatid** [comment]
Not at all, if you put package that require compilation to `optionalDependencies` and if compilation fails, exit code will be still 0..

```
$ cat package.json
{
  "dependencies": {
    "elliptic": "^6.2.3"
  },
  "optionalDependencies": {
    "secp256k1": "^3.0.0"
  }
}
$ CXX=g-- npm i
...
make: g--: Command not found
...
gyp ERR! build error
...
$ echo $?
0
```

**Comment by axic** [comment]
@fanatid I think its a bit nonstandard behaviour to marry the fact `optionalDependencies` still leaves the package if compilation failed.

If it works, it works.  Would be nice to eventually have this as a proper feature in `package.json` or `gyp`.

**Pull request merged**
